[package]
name = "type_script"
version = "0.1.0"
authors = ["Nathan Shively-Sanders <293473+sandersn@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
